#-------------------------------
# General Site Settings
title: Blog by Milos Marinkovic
logo: '/images/brand/logo.png'
description: Embark on a captivating digital journey through my personal blog, where we delve into technology, organization, business, life hacks, and the occasional random rant. Join me as we explore innovation, personal growth, and unexpected discoveries, while experiencing the unique perspectives and opinions that are exclusively my own.
keywords: milos, marinkovic, tech, blog, posts, writing, journal, diary, personal, space, paper, developer, product, lead, engineer, profile, organization, skill
baseurl: "" # subpath, e.g. /blog
url: "https://milos.marinkovic.xyz" # include protocol


#-------------------------------
# Author Settings
author:
  name: Milos Marinkovic
  avatar: '/images/brand/profile.png'


#-------------------------------
# Hero Settings
hero:
  title: Find magic in the ordinary.
  description: A collection of thoughts, stories, ideas.
  image: '/images/brand/hero.jpg'


#-------------------------------
# Contact Settings
contact:
  email: milosmns@gmail.com
  description: Get in touch, easily.

  # NOTE
  # Norlin theme comes with a contact form built-in. 
  # You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free.
  # Also, you can easily switch to another service if you want.


#-------------------------------
# Footer section
# Other icons can be found at https://ionicons.com/v4/
social:
- {icon: "ion-logo-twitter", link: "https://twitter.com/milosmns"}
- {icon: "ion-logo-github", link: "https://github.com/milosmns"}
- {icon: "ion-logo-linkedin", link: "https://linkedin.com/in/milosmns"}
- {icon: "ion-ios-call", link: "https://bit.ly/book-mm"}


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: milosmns-blog


#-------------------------------
# Google Analytics
google-analytics: 'G-K1WJSDTLYR'


#-------------------------------
# Newsletter
mailchimp: # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 8
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed

